# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:title/

# Setup
title:               Jayser Mendez
tagline:             'Full Stack Developer'
description:         'A New York City based hacker with a background in Computer Science and passion to build web applications.'
url:                 'https://jayserdny.github.io'
baseurl:             'https://jayserdny.github.io'
paginate:            20

# About/contact
author:
  name:              Jayser Mendez
  url:               https://www.linkedin.com/in/jaysermendez/
  email:             jayser.mendez@stu.bcc.cuny.edu

# Custom vars
version:             1.0.0

plugins:
  - jekyll-seo-tag
